??=define A /*
??=define AA *
??=define AAA c_apps.c
??=define AAAA Interface
??=define AAAAA of
??=define AAAAAA interface
??=define AAAAAAA c_apps
??=define AAAAAAAA Created
??=define AAAAAAAAA on:
??=define AAAAAAAAAA March
??=define AAAAAAAAAAA 1,
??=define AAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAA //
??=define AAAAAAAAAAAAAAAAA Include
??=define AAAAAAAAAAAAAAAAAA all
??=define AAAAAAAAAAAAAAAAAAA the
??=define AAAAAAAAAAAAAAAAAAAA headers
??=define AAAAAAAAAAAAAAAAAAAAA for
??=define AAAAAAAAAAAAAAAAAAAAAA C
??=define AAAAAAAAAAAAAAAAAAAAAAA applications
??=define AAAAAAAAAAAAAAAAAAAAAAAA here
??=define AAAAAAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA "fs_man/fs_man.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA "media_viewer/media_view.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA "paint/paint.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA "text_editor/text_edit.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "games/2048/2048.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "games/ball/ball.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "games/minesweeper/minesweeper.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "games/snake/snake.h"
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAA
AAAAAAA
AA
AAAAAAAA
AAAAAAAAA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA