??=define A /*
??=define AA *
??=define AAA minesweeper.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA Tangent
??=define AAAAAAA Minesweeper
??=define AAAAAAAA Game
??=define AAAAAAAAA Application
??=define AAAAAAAAAA A
??=define AAAAAAAAAAA simple
??=define AAAAAAAAAAAA minesweeper
??=define AAAAAAAAAAAAA game
??=define AAAAAAAAAAAAAA Tangent,
??=define AAAAAAAAAAAAAAA you
??=define AAAAAAAAAAAAAAAA can
??=define AAAAAAAAAAAAAAAAA do
??=define AAAAAAAAAAAAAAAAAA stuff
??=define AAAAAAAAAAAAAAAAAAA with
??=define AAAAAAAAAAAAAAAAAAAA it.
??=define AAAAAAAAAAAAAAAAAAAAA Created
??=define AAAAAAAAAAAAAAAAAAAAAA on:
??=define AAAAAAAAAAAAAAAAAAAAAAA Feb
??=define AAAAAAAAAAAAAAAAAAAAAAAA 22,
??=define AAAAAAAAAAAAAAAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA MINESWEEPER_H_
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "../../../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA void
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA start_minesweeper(void);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AAAAAAAA
AAAAAAAAA
AA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AAAAAAAAAAAAA
AAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA