??=define A /*
??=define AA *
??=define AAA 2048.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA Tangent
??=define AAAAAAA 2048
??=define AAAAAAAA Game
??=define AAAAAAAAA Application
??=define AAAAAAAAAA A
??=define AAAAAAAAAAA simple
??=define AAAAAAAAAAAA game
??=define AAAAAAAAAAAAA Tangent,
??=define AAAAAAAAAAAAAA you
??=define AAAAAAAAAAAAAAA can
??=define AAAAAAAAAAAAAAAA do
??=define AAAAAAAAAAAAAAAAA stuff
??=define AAAAAAAAAAAAAAAAAA with
??=define AAAAAAAAAAAAAAAAAAA it.
??=define AAAAAAAAAAAAAAAAAAAA Created
??=define AAAAAAAAAAAAAAAAAAAAA on:
??=define AAAAAAAAAAAAAAAAAAAAAA Feb
??=define AAAAAAAAAAAAAAAAAAAAAAA 22,
??=define AAAAAAAAAAAAAAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAAAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA _2048_H_
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "../../../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA void
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA start_2048(void);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AAAAAAAA
AAAAAAAAA
AA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAA
AAAAAAAAAAAA
AAAAA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA