??=define A /*
??=define AA *
??=define AAA input.h
??=define AAAA Interface
??=define AAAAA of
??=define AAAAAA text
??=define AAAAAAA input
??=define AAAAAAAA utilities
??=define AAAAAAAAA +
??=define AAAAAAAAAA on-screen
??=define AAAAAAAAAAA ASCII
??=define AAAAAAAAAAAA keyboard
??=define AAAAAAAAAAAAA Created
??=define AAAAAAAAAAAAAA on:
??=define AAAAAAAAAAAAAAA Feb
??=define AAAAAAAAAAAAAAAA 11,
??=define AAAAAAAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAAAAAAA INPUT_INPUT_H_
??=define AAAAAAAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAAAAA "../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA //
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA Just
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA one
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA function
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA :)
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA byte
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA input_text(char
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *buffer,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA max_len);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AAAAAAAA
AAAAAAAAA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA