??=define A /*
??=define AA *
??=define AAA desktop.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA desktop
??=define AAAAAAA environment
??=define AAAAAAAA Created
??=define AAAAAAAAA on:
??=define AAAAAAAAAA Jan
??=define AAAAAAAAAAA 4,
??=define AAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAA DESKTOP_H_
??=define AAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAA "../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAA Forward
??=define AAAAAAAAAAAAAAAAAAAAAA declaration
??=define AAAAAAAAAAAAAAAAAAAAAAA to
??=define AAAAAAAAAAAAAAAAAAAAAAAA avoid
??=define AAAAAAAAAAAAAAAAAAAAAAAAA pulling
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA in
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA the
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA entire
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA TUI
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA header
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA typedef
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA struct
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA TmlElement
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA TmlElement;
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *desktop_init(void);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA void
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA desktop_render(TmlElement
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *root);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *desktop_get_window(TmlElement
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *desktop_get_time_text(TmlElement
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AA
AAAAAAAA
AAAAAAAAA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA