??=define A /*
??=define AA *
??=define AAA media.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA media
??=define AAAAAAA handling
??=define AAAAAAAA Created
??=define AAAAAAAAA on:
??=define AAAAAAAAAA Jan
??=define AAAAAAAAAAA 4,
??=define AAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAA MEDIA_H_
??=define AAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAA "../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAA typedef
??=define AAAAAAAAAAAAAAAAAAAAAA enum
??=define AAAAAAAAAAAAAAAAAAAAAAA ??<
??=define AAAAAAAAAAAAAAAAAAAAAAAA MEDIA_COMPRESS_LZMA
??=define AAAAAAAAAAAAAAAAAAAAAAAAA =
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA 0,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA MEDIA_COMPRESS_RAW,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA MEDIA_COMPRESS_RLE
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??>
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA media_compression_t;
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA byte
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA show_media(fs_node_t
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *parent,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA const
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA char
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *path,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA media_compression_t
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA method);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA byte*
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA compress_media(const
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA data,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA word
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA size,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA method,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA word*
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA out_size);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AA
AAAAAAAA
AAAAAAAAA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA