??=define A /*
??=define AA *
??=define AAA paint.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA Tangent
??=define AAAAAAA Paint
??=define AAAAAAAA Application
??=define AAAAAAAAA A
??=define AAAAAAAAAA simple
??=define AAAAAAAAAAA paint
??=define AAAAAAAAAAAA application
??=define AAAAAAAAAAAAA Tangent,
??=define AAAAAAAAAAAAAA you
??=define AAAAAAAAAAAAAAA can
??=define AAAAAAAAAAAAAAAA do
??=define AAAAAAAAAAAAAAAAA stuff
??=define AAAAAAAAAAAAAAAAAA with
??=define AAAAAAAAAAAAAAAAAAA it.
??=define AAAAAAAAAAAAAAAAAAAA Created
??=define AAAAAAAAAAAAAAAAAAAAA on:
??=define AAAAAAAAAAAAAAAAAAAAAA Feb
??=define AAAAAAAAAAAAAAAAAAAAAAA 21,
??=define AAAAAAAAAAAAAAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAAAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA PAINT_H_
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "../../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA void
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA start_paint(void);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA paint_open(const
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA char
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *filename);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AAAAAAAA
AA
AAAAAAAAA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AAAAA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA