??=define A /*
??=define AA *
??=define AAA fs_man.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA Tangent
??=define AAAAAAA File
??=define AAAAAAAA System
??=define AAAAAAAAA Manager
??=define AAAAAAAAAA A
??=define AAAAAAAAAAA simple
??=define AAAAAAAAAAAA file
??=define AAAAAAAAAAAAA system
??=define AAAAAAAAAAAAAA manager
??=define AAAAAAAAAAAAAAA Tangent,
??=define AAAAAAAAAAAAAAAA you
??=define AAAAAAAAAAAAAAAAA can
??=define AAAAAAAAAAAAAAAAAA do
??=define AAAAAAAAAAAAAAAAAAA stuff
??=define AAAAAAAAAAAAAAAAAAAA with
??=define AAAAAAAAAAAAAAAAAAAAA it.
??=define AAAAAAAAAAAAAAAAAAAAAA Created
??=define AAAAAAAAAAAAAAAAAAAAAAA on:
??=define AAAAAAAAAAAAAAAAAAAAAAAA Feb
??=define AAAAAAAAAAAAAAAAAAAAAAAAA 21,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA FS_MAN_H_
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "../../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA void
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA start_fs_man(void);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA fs_man_open(const
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA char
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *path);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AAAAAAAA
AAAAAAAAA
AA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA