??=define A /*
??=define AA *
??=define AAA bsod.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA Black
??=define AAAAAAA Screen
??=define AAAAAAAA of
??=define AAAAAAAAA Death
??=define AAAAAAAAAA Created
??=define AAAAAAAAAAA on:
??=define AAAAAAAAAAAA Jan
??=define AAAAAAAAAAAAA 4,
??=define AAAAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAAAA BSOD_H_
??=define AAAAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAA "../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAAAA //
??=define AAAAAAAAAAAAAAAAAAAAAAAA Forward
??=define AAAAAAAAAAAAAAAAAAAAAAAAA declaration
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA typedef
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA enum
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA error_t
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA error_t;
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA void
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA bsod_show(error_t
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA error_code,
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA byte
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *regs_snapshot);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AAAAAAAA
AAAAAAAAA
AA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AAAAAAAAAAAAA
AAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA