??=define A /*
??=define AA *
??=define AAA media_view.h
??=define AAAA Interface
??=define AAAAA for
??=define AAAAAA Tangent
??=define AAAAAAA Media
??=define AAAAAAAA Viewer
??=define AAAAAAAAA Application
??=define AAAAAAAAAA A
??=define AAAAAAAAAAA simple
??=define AAAAAAAAAAAA media
??=define AAAAAAAAAAAAA viewer
??=define AAAAAAAAAAAAAA Tangent,
??=define AAAAAAAAAAAAAAA you
??=define AAAAAAAAAAAAAAAA can
??=define AAAAAAAAAAAAAAAAA do
??=define AAAAAAAAAAAAAAAAAA stuff
??=define AAAAAAAAAAAAAAAAAAA with
??=define AAAAAAAAAAAAAAAAAAAA it.
??=define AAAAAAAAAAAAAAAAAAAAA Created
??=define AAAAAAAAAAAAAAAAAAAAAA on:
??=define AAAAAAAAAAAAAAAAAAAAAAA Feb
??=define AAAAAAAAAAAAAAAAAAAAAAAA 21,
??=define AAAAAAAAAAAAAAAAAAAAAAAAA 2026
??=define AAAAAAAAAAAAAAAAAAAAAAAAAA Author:
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAA harma
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAA */
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=ifndef
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA MEDIA_VIEW_H_
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=define
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=include
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA "../../libcw.h"
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA void
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA start_media_view(void);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA media_view_open(const
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA char
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA *filename);
??=define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ??=endif
A
AA
AAA
AA
AAAA
AAAAA
AAAAAA
AAAAAAA
AAAAAAAA
AAAAAAAAA
AA
AAAAAAAAAA
AAAAAAAAAAA
AAAAAAAAAAAA
AAAAAAAAAAAAA
AAAAA
AAAAAAAAAAAAAA
AAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
AA
AAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
A
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAA